# Generated by Django 4.1.7 on 2023-08-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
